type Theme = Record<string, string>;

const Themes: Record<string, Theme> = {
    black: {
        '--background': '#000000',
        '--text-color': '#ffffff',
        '--cursor-color': '#ffffff',
        '--selection-bg': '#444444',
        '--black':   '#000000',
        '--red':     '#ff1717',
        '--green':   '#39ff14',
        '--yellow':  '#ffff00',
        '--blue':    '#0080ff',
        '--magenta': '#ff00ff',
        '--cyan':    '#00ffff',
        '--white':   '#ffffff',
        '--bright-black':   '#808080',
        '--bright-red':     '#ff5555',
        '--bright-green':   '#55ff55',
        '--bright-yellow':  '#ffff55',
        '--bright-blue':    '#5555ff',
        '--bright-magenta': '#ff55ff',
        '--bright-cyan':    '#55ffff',
        '--bright-white':   '#ffffff',
    },
    dark: {
        '--background': '#1e1e1e',
        '--text-color': '#d4d4d4',
        '--cursor-color': '#d4d4d4',
        '--selection-bg': '#264f78',
        '--black':   '#000000',
        '--red':     '#cd3131',
        '--green':   '#0dbc79',
        '--yellow':  '#e5e510',
        '--blue':    '#3b82f6',
        '--magenta': '#bc3fbc',
        '--cyan':    '#29b8db',
        '--white':   '#e5e5e5',
        '--bright-black':   '#666666',
        '--bright-red':     '#f14c4c',
        '--bright-green':   '#23d186',
        '--bright-yellow':  '#f5f543',
        '--bright-blue':    '#589df6',
        '--bright-magenta': '#d670d6',
        '--bright-cyan':    '#38cde9',
        '--bright-white':   '#ffffff',
    },
    light: {
        '--background': '#ffffff',
        '--text-color': '#000000',
        '--cursor-color': '#000000',
        '--selection-bg': '#bde4ff',
        '--black':   '#000000',
        '--red':     '#c82829',
        '--green':   '#00a200',
        '--yellow':  '#c59000',
        '--blue':    '#0055d4',
        '--magenta': '#c93ac9',
        '--cyan':    '#00a0a0',
        '--white':   '#d0d0d0',
        '--bright-black':   '#777777',
        '--bright-red':     '#ff3f3f',
        '--bright-green':   '#10c710',
        '--bright-yellow':  '#ffff55',
        '--bright-blue':    '#5555ff',
        '--bright-magenta': '#ff55ff',
        '--bright-cyan':    '#55ffff',
        '--bright-white':   '#000000',
    },
};

export const defaultTheme: keyof typeof Themes = "dark";

export default Themes;